In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
raw_train_data = pd.read_csv("train.csv")
raw_train_data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [16]:
raw_test_data = pd.read_csv("test.csv")
raw_test_data.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [17]:
women = raw_train_data.loc[train_data.Sex == 'female']['Survived']
rate_women = sum(women)/len(women)
print(rate_women)

0.7420382165605095


In [18]:
men = raw_train_data.loc[train_data.Sex == 'male']['Survived']
rate_men = sum(men)/len(men)
print(rate_men)

0.18890814558058924


In [44]:
columns_to_drop = ['PassengerId', 'Name', 'Ticket', 'Fare', 'Cabin', 'Embarked']
train_data = raw_train_data.drop(columns_to_drop, axis=1)
print(train_data)

print("llllllllllllllllll")

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(train_data[:,3])


     Survived  Pclass     Sex   Age  SibSp  Parch
0           0       3    male  22.0      1      0
1           1       1  female  38.0      1      0
2           1       3  female  26.0      0      0
3           1       1  female  35.0      1      0
4           0       3    male  35.0      0      0
..        ...     ...     ...   ...    ...    ...
886         0       2    male  27.0      0      0
887         1       1  female  19.0      0      0
888         0       3  female   NaN      1      2
889         1       1    male  26.0      0      0
890         0       3    male  32.0      0      0

[891 rows x 6 columns]
llllllllllllllllll


InvalidIndexError: (slice(None, None, None), 3)

In [36]:
X = train_data.iloc[:,1:].values
y = train_data.iloc[:,:1].values

from sklearn.compose import ColumnTransformer

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
train_data['Sex'] = label_encoder.fit_transform(train_data['Sex'])

print(train_data)


     Survived  Pclass  Sex   Age  SibSp  Parch
0           0       3    1  22.0      1      0
1           1       1    0  38.0      1      0
2           1       3    0  26.0      0      0
3           1       1    0  35.0      1      0
4           0       3    1  35.0      0      0
..        ...     ...  ...   ...    ...    ...
886         0       2    1  27.0      0      0
887         1       1    0  19.0      0      0
888         0       3    0   NaN      1      2
889         1       1    1  26.0      0      0
890         0       3    1  32.0      0      0

[891 rows x 6 columns]


In [37]:
print(X)

[[ 3.  1. 22.  1.  0.]
 [ 1.  0. 38.  1.  0.]
 [ 3.  0. 26.  0.  0.]
 ...
 [ 3.  0. nan  1.  2.]
 [ 1.  1. 26.  0.  0.]
 [ 3.  1. 32.  0.  0.]]


In [39]:
print(y)

[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]


In [42]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,3])

ValueError: Expected 2D array, got 1D array instead:
array=[1. 1. 0. 1. 0. 0. 0. 3. 0. 1. 1. 0. 0. 1. 0. 0. 4. 0. 1. 0. 0. 0. 0. 0.
 3. 1. 0. 3. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 2. 1. 1. 1. 0. 1. 0. 0. 1. 0.
 2. 1. 4. 0. 1. 1. 0. 0. 0. 0. 1. 5. 0. 0. 1. 3. 0. 1. 0. 0. 4. 2. 0. 5.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 1. 0. 3. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 2. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 4.
 2. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.
 0. 1. 0. 2. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 8. 0. 0. 0. 0. 4. 0. 0. 1.
 0. 0. 0. 4. 1. 0. 0. 1. 3. 0. 0. 0. 8. 0. 4. 2. 0. 0. 1. 0. 1. 0. 0. 0.
 1. 1. 0. 0. 0. 0. 0. 0. 0. 8. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1.
 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 3. 1. 0. 0. 4. 0. 0. 1. 0. 0. 0.
 1. 1. 0. 0. 0. 2. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 4. 1. 0.
 0. 0. 4. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 4. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 2. 0. 0. 0. 1. 0. 1. 1. 0. 0. 2.
 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 8. 0. 0. 0. 1. 0. 2. 0. 0. 2. 1. 0.
 1. 0. 0. 0. 1. 3. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 1. 1. 0. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 3. 1. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 5. 0. 0. 0. 1. 0. 2. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.
 0. 3. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1.
 1. 0. 1. 1. 2. 2. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 2. 0. 1. 1. 0. 1. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0.
 5. 0. 0. 0. 1. 3. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 2. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 4. 4. 1. 1. 0. 1. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0.
 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 1.
 2. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 2. 0. 1. 1. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 1. 0. 1. 0. 0. 3. 0. 2. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 2. 0. 1. 0. 0. 2. 0. 0. 0. 1. 2. 0. 0. 0. 1. 1. 1.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 5. 1. 1. 4. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 1. 0. 3. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 2. 1.
 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 4. 1. 0. 0. 0.
 8. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 4. 0. 0.
 0. 1. 0. 3. 1. 0. 0. 0. 4. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 8. 0. 0. 1. 4. 0. 1. 0. 1. 0. 1. 0. 0. 0. 2. 1. 0. 8.
 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [41]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X,y)


ValueError: Input contains NaN, infinity or a value too large for dtype('float64').